// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycykconqgnzurirxpewf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljeWtjb25xZ256dXJpcnhwZXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDMzMTcsImV4cCI6MjA2NjUxOTMxN30.iwTQ_t-b5LbhcF7ASYyAcuaUhqi_clvDz_06FA9bYUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);